baseurl = "https://ishanjain.me"
DefaultContentLanguage = "en"
title = "<title goes here/>"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "personal blog on Computer Graphics, Backend, Image processing and maybe some random topics"
  logo = "img/profile.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  showRelatedPosts = true
  selfHosted = false
  useHLJS = true

[Author]
  name = "Ishan Jain"
  website = "https://ishanjain.me"
  email = "ishanjain28@gmail.com"
  github = "ishanjain28"
  gitlab = "ishanjain"
  twitter = "ishanjain28"
  reddit = "ishanjain28"
  steam = "ishanjain28"
  linkedin = "ishan-jain-ba63b671"
  stackoverflow = "users/5805469/ishan-jain"
  spotify = "ishanjain28"
  telegram = "ishanjain28"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects/projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 4
